[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "426ffabe997f66d993f18075e69e408cf7a5a4cd0d64d6a9d2ae4667efeba4bd"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
