[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "edff03bae4ed39452f98cd7207741828cf218c7d32f6fc876913e7c4b8d62e6e"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
