[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "0331d78e63bb9e6cda72be405b09d16c5a7f5464df3f0a374004656d5596f44c"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
