[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "0x2394ae8e69bd837ac1d946992646e303f5f6507e5cac3f65ee30528668a3d12d"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
