[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "d8cc15e3fa65be6271cfbe263dd29ec214d4ac03296da38f12bd46d4a7eb6e36"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
