[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "880e85921ebde94965dfec4f3afc9252010f50998427ee232bd749be39315ce2"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
