[package]
name = "DonaPay"
version = "1.0.0"
authors = []

[addresses]
dona_pay = "c0292743f90a9dee8171eb0866519c9c4334be377800b40f45551f87fe555f51"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
